{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkUnreachable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/processout\/pofailure\/code-swift.enum\/networkunreachable"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.processout.processout-ios\/documentation\/ProcessOut\/POFailure\/Code-swift.enum\/networkUnreachable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No network connection."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkUnreachable"}],"title":"POFailure.Code.networkUnreachable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:10ProcessOut9POFailureV4CodeO18networkUnreachableyA2EmF","modules":[{"name":"ProcessOut"}]},"hierarchy":{"paths":[["doc:\/\/com.processout.processout-ios\/documentation\/ProcessOut","doc:\/\/com.processout.processout-ios\/documentation\/ProcessOut\/POFailure","doc:\/\/com.processout.processout-ios\/documentation\/ProcessOut\/POFailure\/Code-swift.enum"]]},"references":{"doc://com.processout.processout-ios/documentation/ProcessOut/POFailure":{"role":"symbol","title":"POFailure","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"POFailure"}],"abstract":[{"type":"text","text":"Information about an error that occurred."}],"identifier":"doc:\/\/com.processout.processout-ios\/documentation\/ProcessOut\/POFailure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"POFailure"}],"url":"\/documentation\/processout\/pofailure"},"doc://com.processout.processout-ios/documentation/ProcessOut/POFailure/Code-swift.enum":{"role":"symbol","title":"POFailure.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[],"identifier":"doc:\/\/com.processout.processout-ios\/documentation\/ProcessOut\/POFailure\/Code-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"url":"\/documentation\/processout\/pofailure\/code-swift.enum"},"doc://com.processout.processout-ios/documentation/ProcessOut/POFailure/Code-swift.enum/networkUnreachable":{"role":"symbol","title":"POFailure.Code.networkUnreachable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkUnreachable"}],"abstract":[{"type":"text","text":"No network connection."}],"identifier":"doc:\/\/com.processout.processout-ios\/documentation\/ProcessOut\/POFailure\/Code-swift.enum\/networkUnreachable","kind":"symbol","type":"topic","url":"\/documentation\/processout\/pofailure\/code-swift.enum\/networkunreachable"},"doc://com.processout.processout-ios/documentation/ProcessOut":{"role":"collection","title":"ProcessOut","abstract":[],"identifier":"doc:\/\/com.processout.processout-ios\/documentation\/ProcessOut","kind":"symbol","type":"topic","url":"\/documentation\/processout"}}}